'use strict';

export const HELLO_WORLD = 'HELLO_WORLD';
export const REDUX_RESET_STATE = 'REDUX_RESET_STATE';



// auth constants
export const AUTH_UPDATE_REGISTER_FORM_FIELD = 'AUTH_UPDATE_REGISTER_FORM_FIELD';
export const AUTH_SUBMIT_REGISTER_FORM = 'AUTH_SUBMIT_REGISTER_FORM';
export const AUTH_INVALIDATE_REGISTER_FORM = 'AUTH_INVALIDATE_REGISTER_FORM';
export const AUTH_RESET_REGISTER_FORM_FIELDS = 'AUTH_RESET_REGISTER_FORM_FIELDS';

export const AUTH_UPDATE_USER_DATA = 'AUTH_UPDATE_USER_DATA';
export const AUTH_RESET_USER_DATA = 'AUTH_RESET_USER_DATA';
export const AUTH_UPDATE_USER_FIELD = 'AUTH_UPDATE_USER_FIELD';


export const AUTH_UPDATE_LOGIN_FORM_FIELD = 'AUTH_UPDATE_LOGIN_FORM_FIELD';
export const AUTH_SUBMIT_LOGIN_FORM = 'AUTH_SUBMIT_LOGIN_FORM';
export const AUTH_INVALIDATE_LOGIN_FORM = 'AUTH_INVALIDATE_LOGIN_FORM';
export const AUTH_RESET_LOGIN_FORM_FIELDS = 'AUTH_RESET_LOGIN_FORM_FIELDS';



export const AUTH_SUBMIT_RESET_PASSWORD_FORM = 'AUTH_SUBMIT_RESET_PASSWORD_FORM';
export const AUTH_UPDATE_RESET_PASSWORD_STATUS_FIELD = 'AUTH_UPDATE_RESET_PASSWORD_STATUS_FIELD';
export const AUTH_INVALIDATE_RESET_PASSWORD_FORM = 'AUTH_INVALIDATE_RESET_PASSWORD_FORM';




// app constants
export const APP_CONFIG_TOGGLE_ASIDE = 'APP_CONFIG_TOGGLE_ASIDE';





export const USER_PROFILE_LOADED = 'USER_PROFILE_LOADED';
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const USER_UPDATE_PROFILE_FIELD = 'USER_UPDATE_PROFILE_FIELD';
export const USER_DELETE_PROFILE_FIELD = 'USER_DELETE_PROFILE_FIELD';







// UI MODALS
export const UI_MODALS_UPDATE_FIELD = 'UI_MODALS_UPDATE_FIELD';
export const UI_PROCESSING_UPDATE_FIELD = 'UI_PROCESSING_UPDATE_FIELD';
export const UI_LOADED_UPDATE_FIELD = 'UI_LOADED_UPDATE_FIELD';





export const HOST_CREATE_EVENT_MANY = 'HOST_CREATE_EVENT_MANY';
export const HOST_CREATE_EVENT = 'HOST_CREATE_EVENT';
export const HOST_UPDATE_EVENT = 'HOST_UPDATE_EVENT';
export const HOST_UPDATE_EVENT_SECTION = 'HOST_UPDATE_EVENT_SECTION';
export const HOST_DELETE_EVENT_FIELD = 'HOST_DELETE_EVENT_FIELD';



export const HOST_CREATE_EVENT_ACTION_MANY = 'HOST_CREATE_EVENT_ACTION_MANY';


// export const HOST_UPDATE_EVENT_ACTIONS_CURRENT_TAB = 'HOST_UPDATE_EVENT_ACTIONS_CURRENT_TAB';
export const HOST_UPDATE_EVENT_ACTION = 'HOST_UPDATE_EVENT_ACTION';
export const HOST_CREATE_EVENT_ACTION = 'HOST_CREATE_EVENT_ACTION';




export const HOST_CREATE_ALLAKARTE_MANY = 'HOST_CREATE_ALLAKARTE_MANY';
export const HOST_CREATE_ALLAKARTE = 'HOST_CREATE_ALLAKARTE';
export const HOST_UPDATE_ALLAKARTE = 'HOST_UPDATE_ALLAKARTE';







export const WWW_LOAD_EVENT = 'WWW_LOAD_EVENT';
export const WWW_LOAD_EVENTS = 'WWW_LOAD_EVENTS';
export const WWW_UPDATE_CURRENT_BOOKING_FIELD = 'WWW_UPDATE_CURRENT_BOOKING_FIELD';
export const WWW_RESET_CURRENT_BOOKING_FIELDS = 'WWW_RESET_CURRENT_BOOKING_FIELDS';


export const WWW_LOAD_REVIEWS = 'WWW_LOAD_REVIEWS';

export const WWW_LOAD_HOST = 'WWW_LOAD_HOST';
export const WWW_LOAD_HOSTS = 'WWW_LOAD_HOSTS';
export const WWW_SET_GEO = 'WWW_SET_GEO';



export const USER_CREATE_BOOKING_MANY = 'USER_CREATE_BOOKING_MANY';
export const USER_CREATE_BOOKING = 'USER_CREATE_BOOKING';
export const USER_UPDATE_BOOKING_GUEST_DATA = 'USER_UPDATE_BOOKING_GUEST_DATA';
export const USER_UPDATE_BOOKING_FIELD = 'USER_UPDATE_BOOKING_FIELD';




